server:
  port: 8080

app:
    api:
        prefix: /api/v1
        prefixAI: http://127.0.0.1:8000
    security:
      expiresIn: 6000 # 300 second = 5 minutes
      expiresRefresh: 30000 # 3000 second = 50p
      secret: fEJ6qu3MQ1pwdpRYxhiXNpor7jNV6tCdhw73m9rR5TfH5rS6Zq1tVDsUooXljGi3
    clodinary:
      url: cloudinary://517415745711638:cjlC-HkUHayjU0J18PQzQjL6bvQ@dlwld3eeg
    file:
      prefix: /uploads
vnpay:
  tmnCode: RMEWAEMU
  hashSecret: GSNJ39IBETFV4UBG50R9QZP9GQEDSYMQ
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://13.231.191.87/api/v1/payment/vnpay/return
spring:
    application:
        name: medical_store
    profiles:
        active: dev